# =============================================================================
# src/module_12_stage1p5_regen_selftest.py
# Regenerates app/runtime/feature_builder_selftest.py for the Stage 1.5 builder.
# =============================================================================
# The Stage 1.4 selftest embedded references for the OLD (wrong) column map and
# checked indices 0-19. After Stage 1.5 repoint, it must:
#   - embed references computed by the NEW build_m7_features
#   - check ONLY the 16 bit-exact, gate-proven columns (idx 0-10,12-16,24)
#   - SKIP idx 25-28 (z_t: float16/sign skew) and all stubs (they're 0.0/proxy)
# This keeps C-30 (startup identity guard) meaningful without false alarms.
# =============================================================================

import sys, os, pickle, json
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import SYNTH_DIR, MODEL_DIR
from datetime import datetime
import numpy as np
import torch

def log(m): print(f"[{datetime.now().strftime('%H:%M:%S')}] {m}")

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))
from app.runtime.model_registry import _M4LSTMAutoencoder

# Indices the selftest verifies — the 16 bit-exact, formula-deterministic columns.
CHECK_IDX = [0,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,24]
# Note: idx 11,17-23,29-32 are stubs/patched; 25-28 are z_t (float16/sign skew).
# All excluded — verifying them would false-alarm.

WINDOW_SIZE = 50

# Load M4
m4 = _M4LSTMAutoencoder()
state = torch.load(MODEL_DIR / "lstm_ae_baseline_final.pth", map_location='cpu')
if isinstance(state, dict) and 'state_dict' in state:
    state = state['state_dict']
m4.load_state_dict(state, strict=True)
m4.to('cpu').eval()
log("M4 loaded")

# Load builder
import importlib.util
fb_path = _ROOT / "app" / "runtime" / "feature_builder.py"
spec = importlib.util.spec_from_file_location("feature_builder", fb_path)
fb = importlib.util.module_from_spec(spec); spec.loader.exec_module(fb)

@torch.no_grad()
def run_m4_local(win):
    x = torch.from_numpy(win).float().unsqueeze(0)
    recon = m4(x)
    mae = torch.mean(torch.abs(x - recon), dim=1).squeeze(0)
    enc = m4.encoder
    o1,_ = enc.lstm1(x); o2,(h,c) = enc.lstm2(o1); z = enc.bn(h[-1])
    return mae.cpu().numpy(), z.squeeze(0).cpu().numpy()

# Load 20 reference windows spanning labels (first window of varied sequences)
with open(SYNTH_DIR / "M6B_combined_sequences.pkl", 'rb') as f:
    raw = pickle.load(f)
seqs = raw['sequences'] if isinstance(raw, dict) and 'sequences' in raw else raw
def get_seq(e):
    if isinstance(e, dict):
        for k in ('sequence','seq','data'):
            if k in e: return e[k]
        for v in e.values():
            if isinstance(v, np.ndarray): return v
    return e

# pick 20 sequences spread across the pool
idxs = list(range(0, len(seqs), max(1, len(seqs)//20)))[:20]
refs = []
for si in idxs:
    seq = np.asarray(get_seq(seqs[si]), dtype=np.float32)
    if seq.ndim != 2 or seq.shape[1] != 8 or seq.shape[0] < WINDOW_SIZE:
        continue
    win = seq[:WINDOW_SIZE]
    mae, z = run_m4_local(win)
    fv = fb.build_m7_features(mae, win, z)
    refs.append({
        "seq_idx": int(si),
        "window": win.tolist(),
        "expected": [float(fv[i]) for i in CHECK_IDX],
    })
log(f"Built {len(refs)} reference windows")

# Write the selftest module
selftest_src = '''# =============================================================================
# app/runtime/feature_builder_selftest.py
# C-30 startup identity guard — Stage 1.5 version.
# Verifies build_m7_features reproduces the 16 bit-exact columns on embedded
# reference windows. Raises RuntimeError on mismatch -> server refuses to start.
# Regenerated by src/module_12_stage1p5_regen_selftest.py.
# =============================================================================
import sys
import numpy as np

# 16 bit-exact, formula-deterministic feature indices (Stage 1.5 gate-proven).
# Excludes idx 11,17-23,29-32 (stub/patched) and 25-28 (z_t float16/sign skew).
_CHECK_IDX = ''' + repr(CHECK_IDX) + '''
_TOL = 1e-05

_REFERENCES = ''' + json.dumps(refs) + '''


def run_startup_selftest(m4_model, seqs_list=None, meta_list=None):
    """Verify the builder against embedded references. Raise on mismatch."""
    import torch
    fb = sys.modules.get("app.runtime.feature_builder")
    if fb is None:
        from app.runtime import feature_builder as fb

    @torch.no_grad()
    def _run_m4(win):
        x = torch.from_numpy(np.asarray(win, dtype=np.float32)).float().unsqueeze(0)
        recon = m4_model(x)
        mae = torch.mean(torch.abs(x - recon), dim=1).squeeze(0)
        enc = m4_model.encoder
        o1, _ = enc.lstm1(x); o2, (h, c) = enc.lstm2(o1); z = enc.bn(h[-1])
        return mae.cpu().numpy(), z.squeeze(0).cpu().numpy()

    n_fail = 0
    for ref in _REFERENCES:
        win = np.asarray(ref["window"], dtype=np.float32)
        mae, z = _run_m4(win)
        fv = fb.build_m7_features(mae, win, z)
        got = np.array([float(fv[i]) for i in _CHECK_IDX])
        exp = np.array(ref["expected"], dtype=np.float64)
        md = float(np.max(np.abs(got - exp)))
        if md >= _TOL:
            n_fail += 1
            print(f"[selftest] MISMATCH seq={ref['seq_idx']} max_diff={md:.2e} >= tol={_TOL:.0e}")

    if n_fail:
        raise RuntimeError(
            f"[selftest] FAIL — {n_fail}/{len(_REFERENCES)} windows diverged. "
            f"feature_builder no longer matches embedded reference. Aborting startup."
        )
    print(f"[selftest] PASS — {len(_REFERENCES)} windows verified (16 bit-exact cols)")
'''

out_path = _ROOT / "app" / "runtime" / "feature_builder_selftest.py"
with open(out_path, "w", encoding="utf-8") as f:
    f.write(selftest_src)
log(f"Wrote {out_path}")

# Self-verify: clean run passes, poison fails
sys.modules.pop("feature_builder_selftest", None)
spec2 = importlib.util.spec_from_file_location("feature_builder_selftest", out_path)
st = importlib.util.module_from_spec(spec2); spec2.loader.exec_module(st)

# inject builder into sys.modules so selftest finds it
import types
sys.modules["app.runtime.feature_builder"] = fb

log("Gate A — clean run:")
st.run_startup_selftest(m4)

log("Gate B — poisoned builder:")
_orig = fb.build_m7_features
def _poison(mae, win, z, *a, **k):
    v = _orig(mae, win, z, *a, **k); v[0] += 999.0; return v
fb.build_m7_features = _poison
try:
    st.run_startup_selftest(m4)
    log("  ERROR: poison did not raise — selftest broken")
except RuntimeError:
    log("  Gate B PASS — RuntimeError raised on poison")
finally:
    fb.build_m7_features = _orig

log("Selftest regeneration complete.")
