"""
physics_engine.py - PumpSmart Physics Library
Auto-generated by module_05_physics_engine.py
DO NOT EDIT MANUALLY - regenerate via M5.

Exposes:
    CHANNEL_ORDER, CH_IDX, CLUSTER_BASELINES, WINSOR_CEILINGS
    fault_bearing_wear, fault_impeller_imbalance, fault_cavitation,
    fault_seal_failure, fault_overloading, fault_sensor_failure,
    validate_sequence, FAULT_RULES_PATH, SENSOR_SUBTYPES
"""

from pathlib import Path
import numpy as np
import json
from scipy.stats import pearsonr

_HERE            = Path(__file__).resolve().parent
FAULT_RULES_PATH = _HERE.parent / "models" / "fault_rules.json"
M5_CONFIG_PATH   = _HERE.parent / "models" / "M5_physics_config.json"

with open(M5_CONFIG_PATH, "r") as _f:
    _CFG = json.load(_f)

CHANNEL_ORDER     = _CFG["channel_order"]
CH_IDX            = {ch: i for i, ch in enumerate(CHANNEL_ORDER)}
CLUSTER_BASELINES = _CFG["cluster_baselines"]
WINSOR_CEILINGS   = _CFG["winsor_ceilings"]
NOISE_STD         = _CFG["noise_std"]
T_SEQ             = _CFG["seq_length"]
t_arr             = np.arange(T_SEQ, dtype=np.float64)

_PC = _CFG["physics_constants"]
RHO          = _PC["RHO"]
G            = _PC["G"]
OMEGA        = _PC["OMEGA_rad_s"]
Q_BEP        = _PC["Q_BEP_m3s"]
H_BEP        = _PC["H_BEP_m"]
P_MOTOR_W    = _PC["P_MOTOR_W"]
ETA_OVERALL  = _PC["ETA_OVERALL"]
TAU_THERMAL  = _PC["TAU_THERMAL_s"]
P_VAPOUR_BAR = _PC["P_VAPOUR_BAR"]
A_WAVE       = _PC["A_WAVE_m_s"]
MC_P_MOTOR   = 175000.0
HA_MOTOR     = 450.0
ALPHA_SEAL   = 2e-10
A_GAP_INIT   = 1e-8
CD_SEAL      = 0.61
PIPE_AREA    = np.pi * (0.10 / 2) ** 2
MU_BEARING_HEALTHY = 0.001
SENSOR_SUBTYPES    = ["flatline", "spike", "drift", "dropout"]

def _noise(arr, ch, rng):
    return arr + rng.normal(0, NOISE_STD[ch], size=arr.shape)

def _thermal(t, P, T0, Tinf=20.0):
    return Tinf + (P/HA_MOTOR)*(1-np.exp(-t/TAU_THERMAL)) + (T0-Tinf)*np.exp(-t/TAU_THERMAL)

def _tcoup(MotTV, r=0.9793, ref=0.5):
    return ref + r * (MotTV - ref)

def _bernoulli(P1, P2):
    return np.sqrt(max(2*(P1-P2)*1e5/RHO, 0.0))

def _ns_diss(mu, dudy, vol):
    return mu * dudy**2 * vol


def fault_bearing_wear(cluster="steady_state", severity=0.6, seed=42):
    rng=np.random.default_rng(seed); bl=CLUSTER_BASELINES[cluster]
    ceil=WINSOR_CEILINGS; seq=np.ones((T_SEQ,8),dtype=np.float64)
    for i,ch in enumerate(CHANNEL_ORDER): seq[:,i]=bl.get(ch,1.0)
    beta=max(severity*np.log(max(0.80*ceil["Mot_SV"][cluster],1.25))/T_SEQ,0.003)
    MotSV=np.clip(np.exp(beta*t_arr),0.0,ceil["Mot_SV"][cluster])
    MotPV=np.clip(1.0+0.45*(MotSV-1.0),0.8,ceil["Mot_PV"][cluster])
    # PATCH 3: Euler integration of time-varying Q_brg_t
    F=0.3*P_MOTOR_W/(OMEGA*0.05); v=OMEGA*0.05
    Q0=MU_BEARING_HEALTHY*F*v
    Q_brg_t=Q0*np.exp(beta*0.6*t_arr)*severity
    T_inf=bl["raw_MotTV_min"]+2.0; T_init=bl["raw_MotTV_mean"]
    rng_TV=max(bl["raw_MotTV_max"]-bl["raw_MotTV_min"],1.0)
    T_raw=np.empty(T_SEQ,dtype=np.float64); T_raw[0]=T_init
    for _t in range(1,T_SEQ):
        dT=(Q_brg_t[_t]/HA_MOTOR)-(T_raw[_t-1]-T_inf)/TAU_THERMAL
        T_raw[_t]=T_raw[_t-1]+dT
    MotTV=np.clip((T_raw-T_inf)/rng_TV,-0.05,1.5)
    TempSV=np.clip(_tcoup(MotTV,ref=bl["Temp_SV"]),-0.05,1.5)
    lag=int(rng.integers(5,16)); PmpSV=np.ones(T_SEQ)
    PmpSV[lag:]=np.clip(1.0+0.55*severity*(MotSV[:-lag]-1.0),0.8,ceil["Pmp_SV"][cluster])
    PmpPV=np.clip(1.0+0.8882*(PmpSV-1.0)*0.5,0.8,ceil["Pmp_PV"][cluster])
    PmpTV=np.clip(bl["Pmp_TV"]+0.15*severity*(MotTV-bl["Mot_TV"]),-0.05,1.3)
    PresSV=np.clip(1.0-0.04*severity*(t_arr/T_SEQ),0.3,ceil["Pres_SV"][cluster])
    for i,(arr,ch) in enumerate(zip(
        [MotPV,MotSV,MotTV,PmpPV,PmpSV,PmpTV,TempSV,PresSV],CHANNEL_ORDER)):
        seq[:,i]=_noise(arr,ch,rng)
    return seq.astype(np.float32)


def fault_impeller_imbalance(cluster="steady_state", severity=0.6, seed=42):
    rng=np.random.default_rng(seed); bl=CLUSTER_BASELINES[cluster]
    ceil=WINSOR_CEILINGS; seq=np.ones((T_SEQ,8),dtype=np.float64)
    for i,ch in enumerate(CHANNEL_ORDER): seq[:,i]=bl.get(ch,1.0)
    PmpPV=np.clip(1.0+severity*(ceil["Pmp_PV"][cluster]-1.0)*0.75*(t_arr/T_SEQ),
                  0.9,ceil["Pmp_PV"][cluster])
    AM=severity*0.8*(t_arr/T_SEQ)
    PmpSV=np.clip(np.maximum(1.0+AM*np.abs(np.sin(2*np.pi*0.25*t_arr)),
                             1.0+0.8882*(PmpPV-1.0)),0.9,ceil["Pmp_SV"][cluster])
    PresSV=np.clip(1.0+severity*0.4*(t_arr/T_SEQ)*np.sin(2*np.pi*0.15*t_arr),
                   0.5,ceil["Pres_SV"][cluster])
    lag=int(rng.integers(5,11)); MotPV=np.ones(T_SEQ)
    MotPV[lag:]=np.clip(1.0+0.30*severity*(PmpPV[:-lag]-1.0),0.9,ceil["Mot_PV"][cluster])
    MotSV=np.clip(1.0+0.20*severity*(PmpSV-1.0),0.9,ceil["Mot_SV"][cluster])
    Phi=_ns_diss(1e-3,OMEGA*0.07,1e-4)
    dT=severity*Phi*T_SEQ/(MC_P_MOTOR*0.01)
    MotTV=np.clip(bl["Mot_TV"]+dT*(t_arr/T_SEQ)*0.1,0.0,1.3)
    TempSV=_tcoup(MotTV,ref=bl["Temp_SV"])
    PmpTV=np.clip(bl["Pmp_TV"]+0.08*severity*(t_arr/T_SEQ),0.0,1.3)
    for i,(arr,ch) in enumerate(zip(
        [MotPV,MotSV,MotTV,PmpPV,PmpSV,PmpTV,TempSV,PresSV],CHANNEL_ORDER)):
        seq[:,i]=_noise(arr,ch,rng)
    return seq.astype(np.float32)


def fault_cavitation(cluster="startup", severity=0.6, seed=42):
    assert cluster=="startup","Cavitation locked to startup cluster"
    rng=np.random.default_rng(seed); bl=CLUSTER_BASELINES[cluster]
    ceil=WINSOR_CEILINGS; seq=np.ones((T_SEQ,8),dtype=np.float64)
    for i,ch in enumerate(CHANNEL_ORDER): seq[:,i]=bl.get(ch,1.0)
    t_on=int((1-severity)*0.5*T_SEQ)
    PresSV=np.ones(T_SEQ)
    for t in range(T_SEQ):
        if t>=t_on:
            PresSV[t]=max(1.0-severity*0.6*(t-t_on)/(T_SEQ-t_on)+rng.normal(0,severity*0.3),0.05)
    PresSV=np.clip(PresSV,0.02,ceil["Pres_SV"][cluster])
    p_sp=min(0.05+severity*0.35,0.60); PmpSV=np.ones(T_SEQ)
    for t in range(T_SEQ):
        if t>=t_on:
            bv=_bernoulli(float(PresSV[t]*bl["raw_Pres_mean"]),P_VAPOUR_BAR)
            if rng.random()<p_sp:
                PmpSV[t]=1.0+severity*3.5*min(bv/10.0,1.0)*rng.uniform(0.3,1.0)
            else: PmpSV[t]=1.0+0.10*rng.random()
    PmpSV=np.clip(PmpSV,0.5,ceil["Pmp_SV"][cluster])
    ce=np.cumsum(np.maximum(PmpSV-1.0,0.0))
    PmpTV=np.clip(bl["Pmp_TV"]+severity*0.003*ce,0.0,1.4)
    PmpPV=np.clip(1.0+0.20*severity*(t_arr/T_SEQ),0.9,ceil["Pmp_PV"][cluster])
    MotSV=1.0+0.08*severity*np.random.default_rng(seed+1).random(T_SEQ)
    MotPV=1.0+0.05*severity*(t_arr/T_SEQ)
    MotTV=bl["Mot_TV"]*np.ones(T_SEQ)+0.03*severity*(t_arr/T_SEQ)
    TempSV=_tcoup(MotTV,ref=bl["Temp_SV"])
    for i,(arr,ch) in enumerate(zip(
        [MotPV,MotSV,MotTV,PmpPV,PmpSV,PmpTV,TempSV,PresSV],CHANNEL_ORDER)):
        seq[:,i]=_noise(arr,ch,rng)
    return seq.astype(np.float32)


def fault_seal_failure(cluster="steady_state", severity=0.6, seed=42):
    rng=np.random.default_rng(seed); bl=CLUSTER_BASELINES[cluster]
    ceil=WINSOR_CEILINGS; seq=np.ones((T_SEQ,8),dtype=np.float64)
    for i,ch in enumerate(CHANNEL_ORDER): seq[:,i]=bl.get(ch,1.0)
    A_gap=A_GAP_INIT+ALPHA_SEAL*t_arr*severity
    dP_t=np.maximum(bl["raw_Pres_mean"]*(1.0-severity*0.5*t_arr/T_SEQ),0.5)
    Qlk=np.array([CD_SEAL*A_gap[t]*np.sqrt(max(2*dP_t[t]*1e5/RHO,0.0)) for t in range(T_SEQ)])
    PresSV=np.clip(1.0-severity*0.006*t_arr,0.15,ceil["Pres_SV"][cluster])
    gh=1e-5
    dudy=np.clip(np.array([Qlk[t]/(A_gap[t]*gh+1e-15) for t in range(T_SEQ)]),0,1e6)
    Phi=_ns_diss(1e-3,dudy.mean(),(A_gap*gh).mean())
    dTV=severity*Phi/(MC_P_MOTOR*0.002)*t_arr
    PmpTV=np.clip(bl["Pmp_TV"]+dTV/(bl["raw_PmpTV_max"]-bl["raw_PmpTV_min"]),0.0,1.4)
    PmpPV=np.clip(1.0+0.15*severity*(1.0-PresSV),0.9,ceil["Pmp_PV"][cluster])
    PmpSV=np.clip(1.0+0.12*severity*(t_arr/T_SEQ),0.9,ceil["Pmp_SV"][cluster])
    MotPV=np.ones(T_SEQ)+0.04*rng.random(T_SEQ)
    MotSV=np.ones(T_SEQ)+0.06*rng.random(T_SEQ)
    MotTV=bl["Mot_TV"]*np.ones(T_SEQ)
    TempSV=_tcoup(MotTV,ref=bl["Temp_SV"])
    for i,(arr,ch) in enumerate(zip(
        [MotPV,MotSV,MotTV,PmpPV,PmpSV,PmpTV,TempSV,PresSV],CHANNEL_ORDER)):
        seq[:,i]=_noise(arr,ch,rng)
    return seq.astype(np.float32)


def fault_overloading(cluster="steady_state", severity=0.6, seed=42):
    assert cluster=="steady_state","Overloading locked to steady_state"
    rng=np.random.default_rng(seed); bl=CLUSTER_BASELINES[cluster]
    ceil=WINSOR_CEILINGS; seq=np.ones((T_SEQ,8),dtype=np.float64)
    for i,ch in enumerate(CHANNEL_ORDER): seq[:,i]=bl.get(ch,1.0)
    Q=Q_BEP*(1.0+severity*0.25); eta=max(ETA_OVERALL*(1.0-severity*0.15),0.25)
    Phyd=RHO*G*Q*H_BEP; Psh=Phyd/eta; Pex=max(Psh-P_MOTOR_W,0.0)
    Phi=_ns_diss(1e-3,OMEGA*0.07*(1+severity*0.5),0.5e-3)
    v0=Q_BEP/PIPE_AREA; v1=Q/PIPE_AREA
    Ptot=(Pex+Phi+0.5*RHO*abs(v1**2-v0**2)*Q)*severity
    T0=bl["raw_Temp_min"]+(bl["raw_Temp_max"]-bl["raw_Temp_min"])*bl["Temp_SV"]
    Tr=_thermal(t_arr,Ptot,T0,25.0)
    TempSV=np.clip((Tr-bl["raw_Temp_min"])/(bl["raw_Temp_max"]-bl["raw_Temp_min"]),0.0,1.6)
    Tm=_thermal(t_arr,Ptot*1.1,T0+2,25.0)
    MotTV=np.clip((Tm-bl["raw_MotTV_min"])/(bl["raw_MotTV_max"]-bl["raw_MotTV_min"]),0.0,1.6)
    MotSV=np.clip(np.ones(T_SEQ)+rng.normal(0,0.04,T_SEQ),0.80,ceil["Mot_SV"][cluster])
    PmpSV=np.clip(np.ones(T_SEQ)+rng.normal(0,0.05,T_SEQ),0.80,ceil["Pmp_SV"][cluster])
    MotPV=np.clip(1.0+0.08*severity*(t_arr/T_SEQ),0.9,ceil["Mot_PV"][cluster])
    PmpPV=np.clip(1.0+0.10*severity*(t_arr/T_SEQ),0.9,ceil["Pmp_PV"][cluster])
    lag=20; PmpTV=np.ones(T_SEQ)*bl["Pmp_TV"]
    PmpTV[lag:]=np.clip(bl["Pmp_TV"]+0.80*(MotTV[:-lag]-bl["Mot_TV"]),0.0,1.5)
    H_rat=min((Q/Q_BEP)**2*(1-severity*0.1),ceil["Pres_SV"][cluster])
    PresSV=np.ones(T_SEQ)*H_rat
    for i,(arr,ch) in enumerate(zip(
        [MotPV,MotSV,MotTV,PmpPV,PmpSV,PmpTV,TempSV,PresSV],CHANNEL_ORDER)):
        seq[:,i]=_noise(arr,ch,rng)
    return seq.astype(np.float32)


def fault_sensor_failure(cluster="steady_state", severity=0.6, seed=42,
                         target_channel=None, subtype=None):
    rng=np.random.default_rng(seed); bl=CLUSTER_BASELINES[cluster]
    seq=np.ones((T_SEQ,8),dtype=np.float64)
    for i,ch in enumerate(CHANNEL_ORDER):
        seq[:,i]=_noise(np.full(T_SEQ,bl.get(ch,1.0)),ch,rng)
    if target_channel is None: target_channel=rng.choice(CHANNEL_ORDER)
    if subtype is None: subtype=rng.choice(SENSOR_SUBTYPES)
    idx=CH_IDX[target_channel]; bv=bl.get(target_channel,1.0)
    cv=WINSOR_CEILINGS.get(target_channel,{}).get(cluster,3.0)
    if subtype=="flatline":
        on=int(rng.integers(20,80)); seq[on:,idx]=seq[on-1,idx]
    elif subtype=="spike":
        # PATCH 5: guard against high < low crash
        on=int(rng.integers(10,T_SEQ-30)); dur=int(rng.integers(3,25))
        spike_lo=2.5; spike_hi=max(min(4.0,cv),spike_lo+0.1)
        seq[on:on+dur,idx]=bv*rng.uniform(spike_lo,spike_hi)
        if rng.random()>0.4:
            seq[on+dur:,idx]=bv+rng.normal(0,NOISE_STD[target_channel],T_SEQ-on-dur)
    elif subtype=="drift":
        on=int(rng.integers(0,40)); de=rng.choice([0.0,3.0*bv])
        seq[on:,idx]=np.linspace(bv,de,T_SEQ-on)+rng.normal(
            0,NOISE_STD[target_channel]*0.5,T_SEQ-on)
    elif subtype=="dropout":
        on=int(rng.integers(5,60)); seq[on:,idx]=0.0
    return seq.astype(np.float32), target_channel, subtype


def validate_sequence(seq, fault_type, cluster, target_ch=None):
    bl=CLUSTER_BASELINES[cluster]; gates={}
    gates["G1_no_negative_pressure"]=bool(np.all(seq[:,CH_IDX["Pres_SV"]]>=-0.01))
    gates["G2_temp_floor"]=bool(np.all(
        seq[:,[CH_IDX["Mot_TV"],CH_IDX["Pmp_TV"],CH_IDX["Temp_SV"]]]>=-0.12))
    gates["G3_sv_ceiling"]=bool(
        np.all(seq[:,CH_IDX["Mot_SV"]]<=WINSOR_CEILINGS["Mot_SV"][cluster]+0.1) and
        np.all(seq[:,CH_IDX["Pmp_SV"]]<=WINSOR_CEILINGS["Pmp_SV"][cluster]+0.1))
    if fault_type=="bearing_wear":
        r,_=pearsonr(seq[:,CH_IDX["Mot_TV"]],seq[:,CH_IDX["Mot_SV"]])
        gates["G4_bearing_thermal_coupling"]=bool(r>=0.70)
    else: gates["G4_bearing_thermal_coupling"]=True
    if fault_type=="impeller_imbalance":
        r,_=pearsonr(seq[:,CH_IDX["Pmp_PV"]],seq[:,CH_IDX["Pmp_SV"]])
        gates["G5_impeller_disp_vel_coupling"]=bool(r>=0.70)
    else: gates["G5_impeller_disp_vel_coupling"]=True
    if fault_type=="overloading":
        r,_=pearsonr(seq[:,CH_IDX["Temp_SV"]],seq[:,CH_IDX["Mot_TV"]])
        gates["G6_overload_thermal_coupling"]=bool(r>=0.85)
    else: gates["G6_overload_thermal_coupling"]=True
    if fault_type=="sensor_failure" and target_ch:
        devs=[np.abs(seq[:,CH_IDX[ch]]-bl.get(ch,1.0)).mean()
              for ch in CHANNEL_ORDER if ch!=target_ch]
        gates["G7_sensor_isolation"]=bool(max(devs)<0.20)
    else: gates["G7_sensor_isolation"]=True
    return gates, all(gates.values())
